version: '3.2'
services:
  tests:
    image: jticker/controller-tests
    build:
      context: .
      dockerfile: Dockerfile.tests
    stdin_open: true
    tty: true
    volumes:
      - './:/app'
    ports:
      - "9001:8000"
    networks:
      - jassets_default
      - default
networks:
  jassets_default:
    external: true
